name: Unit_Test

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ["amd64", "arm", "arm64"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: technote-space/get-diff-action@v5
        id: git_diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Build
        run: GOARCH=${{ matrix.go-arch }} LEDGER_ENABLED=false make build

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV

      - name: Go Test
        run: go test -count=1 $(go list ./...) -tags='norace ledger test_ledger_mock'
